inherit_from: .rubocop_todo.yml

inherit_gem:
  rubocop-ruby3_0: rubocop.yml

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes
